# Generated by Django 5.0.2 on 2024-02-22 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qwine", "0002_alter_vin_couleur_alter_vin_pays"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vin",
            name="degree",
            field=models.FloatField(
                db_index=True,
                validators=[
                    django.core.validators.MaxValueValidator(50),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
