# Generated by Django 5.0.2 on 2024-02-22 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qwine", "0003_alter_vin_degree"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cepage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CepagePercentage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cepage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="qwine.cepage"
                    ),
                ),
                (
                    "object_with_cepage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="qwine.vin"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vin",
            name="cepages",
            field=models.ManyToManyField(
                through="qwine.CepagePercentage", to="qwine.cepage"
            ),
        ),
    ]
