# Generated by Django 5.0.2 on 2024-02-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qwine", "0006_remove_vin_cepages_vin_cep_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vin",
            name="cep_test",
        ),
        migrations.AddField(
            model_name="vin",
            name="cepages",
            field=models.ManyToManyField(to="qwine.cepage"),
        ),
        migrations.DeleteModel(
            name="CepagePercentage",
        ),
    ]
