# Generated by Django 5.0.2 on 2024-02-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qwine", "0011_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Inventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveSmallIntegerField()),
                (
                    "cave",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qwine.cave",
                    ),
                ),
                (
                    "vin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="qwine.vin"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
