# Generated by Django 5.0.2 on 2024-02-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qwine", "0012_cave_inventaire_delete_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vin",
            name="user",
        ),
    ]
