# Generated by Django 5.0.2 on 2024-02-22 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qwine", "0016_alter_inventaire_vin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventaire",
            name="vin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="qwine.vin"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventaire",
            constraint=models.UniqueConstraint(
                fields=("vin", "cave"), name="unique_vin_cave_combination"
            ),
        ),
    ]
